name: widget_preview_scaffold
description: Scaffolding for Flutter Widget Previews
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.13.3
dependencies:
  dtd: ^4.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  google_fonts: ^8.2.1
  json_rpc_2: ^4.1.0
  path: ^1.9.1
  stack_trace: ^1.12.2
  url_launcher: ^6.3.2
  web: ^1.1.1
  webview_flutter: ^4.14.1
  webview_flutter_web: ^0.2.3+4
  zaragoza_cultura_app:
    path: C:\Users\Jesús\Zaragoza Cultura App
flutter:
  uses-material-design: true
dependency_overrides:
  zaragoza_cultura_app:
    path: C:\Users\Jesús\Zaragoza Cultura App
